### ISSUE TITLE
Field Maps App- Editable AGOL Hosted Feature Layer View not editable in app

### ISSUE THREAD

**Issue by AmandaHuber** [doug-m/field-maps-testing#26] opened 2020-09-24 16:35 UTC
### Issue
My editable feature layer view is editable everywhere else but in the Field Maps app- blue add button is not visible nor can i edit existing records. 

### Expected Behavior
For the data to be editable from the field app. 

### Map and Credentials
*Group Name: Field Maps Holistic
*Map Name: Regional Trail Incidents MAP

### Steps to Reproduce
Open map in app

### Device Information
iPhone 11

#### Mobile (please complete the following information):
iPhone 11
OS:13.7

### Screenshots
![IMG_2329](https://user-images.githubusercontent.com/62111701/94173768-0275ae80-fe5a-11ea-9cda-4aa5eac5ba01.PNG)
![IMG_2330](https://user-images.githubusercontent.com/62111701/94173774-03a6db80-fe5a-11ea-9383-60b36fea9db9.PNG)

**Comment by miaogeng** [comment] 2020-09-26 00:12
@AmandaHuber I can reproduce the issue. I have logged an issue internally. It will be good that you can keep that map and we can take a look. Also I notice when I save the map as a new copy. The copy map works ok in my device.  
Note: iOS 4042.

**Comment by miaogeng** [comment] 2020-09-30 06:58
@AmandaHuber We have looked into it. It is due to  "Use in ArcGIS Collector" is uncheck at webmap setting. For backwards compatibility, we don't allow you to edit at Field Maps app but just view. If you check that option, it should work.

**Comment by miaogeng** [comment] 2020-09-30 06:58
Let us know if you have additional feedback Close it for now as by design.

**Closed as completed by miaogeng** 2020-09-30 06:58 UTC
Labels: A-bug, B-in product plan, c-by design, mobile
